### ISSUE TITLE
Module not found when executing the command "ts-node example/switchMap.ts"

### ISSUE THREAD

**Issue by xie-qianyue** [Brooooooklyn/learning-rxjs#5]
When I tried to execute the command below:

`npm i -g ts-node && ts-node example/switchMap.ts`

to see the execution result of `switchMap`, I had this error:

```
Error: Cannot find module 'typescript'   
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at load (/usr/lib/node_modules/ts-node/src/index.ts:184:27)
    at service (/usr/lib/node_modules/ts-node/src/index.ts:363:32)
    at Object.register (/usr/lib/node_modules/ts-node/src/index.ts:372:5)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/src/_bin.ts:147:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Is there something I missed to install?

**Comment by Brooooooklyn** [comment]
Maybe you should also run 

``` bash
npm i -g typescript@latest
```

**Comment by xie-qianyue** [comment]
Thank you @Brooooooklyn !
It works.
